### ISSUE TITLE
Using deprecated APIs

### ISSUE THREAD

**Issue by kemelzaidan** [jefkoslowski/gitignore-snippets#4]
The last version of my Atom is not loading the package "due to using deprecated APIs". I'd try to fix it myself, but I couldn't find a way (mainly a log) of what is wrong.

**Comment by jefkoslowski** [comment]
Sorry about that, already investigating the issue. I think its an Atom mistake (https://github.com/atom/atom/issues/6867#issuecomment-112959821).

**Comment by jefkoslowski** [comment]
Hi @kemelzaidan, due to an issue on apm, the latest version (0.2.3) wasn't properly published. Update to version 0.2.4 and you should be ok.

Let me know.
